image: alpine/latest
packages:
  - go
  - task
tasks:
  - test: |
      task test
  - coverage: |
      task test:cov:report -- coverage.txt
  - codecov: |
      bash <(curl -s https://codecov.io/bash)
