image: alpine/edge
packages:
  - go
  - git
  - curl
  - bash
sources:
  - https://git.sr.ht/~kyoto-framework/kyoto
tasks:
  - taskfile: |
      GOBIN=/home/build/ go install github.com/go-task/task/v3/cmd/task@latest
  - test: |
      cd kyoto
      /home/build/task test
