image: alpine/latest
packages:
  - go
  - git
  - curl
sources:
  - https://git.sr.ht/~kyoto-framework/kyoto
tasks:
  - taskfile: |
      GOBIN=/usr/local/bin/ go install github.com/go-task/task/v3/cmd/task@latest
  - test: |
      cd kyoto
      task test
  - coverage: |
      cd kyoto
      task test:cov:report -- coverage.txt
  - codecov: |
      cd kyoto
      bash <(curl -s https://codecov.io/bash)
