site_name: kyoto
site_url: https://kyoto.codes/
site_author: Yurii Zinets
site_description: >-
  Library that brings frontend-like components experience to the server side

repo_url: https://github.com/kyoto-framework/kyoto
repo_name: kyoto-framework/kyoto
edit_uri: ""

theme:
  name: material
  logo: assets/kyoto.svg
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.annotate
  
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - admonition

nav:
  - Home: index.md
  - Prologue: prologue.md
  - Getting started:
    - getting-started/index.md
    - From scratch: getting-started/from-scratch.md
    - With starter: getting-started/with-starter.md
    - Integration: getting-started/integration.md
    - Example with guide: getting-started/example-with-guide.md
  - Basics:
    - basics/index.md
    - Routing: basics/routing.md
    - Pages: basics/pages.md
    - Components: basics/components.md
    - Lifecycle: basics/lifecycle.md
    - Context: basics/components.md
  - Features:
    - features/index.md
    - Actions: features/actions.md
    - Struct Mode: features/struct-mode.md
  - Concepts:
    - concepts/index.md
    - Core: concepts/core.md
    - Scheduler: concepts/scheduler.md
    - State: concepts/state.md
    - Context: concepts/context.md
    - Modules:
      - General: concepts/modules/general.md
      - Adapters: concepts/modules/adapters.md
      - Patching: concepts/modules/patching.md
