version: '3'

tasks:

  test:
    cmds:
      - go test -race . ./actions ./helpers ./lifecycle ./render ./smode

  coverage:
    cmds:
      - go test -cover . ./actions ./helpers ./lifecycle ./render ./smode

  coverage:web:
    cmds:
      - go test -coverprofile /tmp/kyoto-coverage.out . ./actions ./helpers ./lifecycle ./render ./smode
      - go tool cover -html=/tmp/kyoto-coverage.out
      - sleep 3 && rm /tmp/kyoto-coverage.out

  coverage:report:
    cmds:
      - go test -race -coverprofile=/tmp/coverage.txt.tmp -covermode=atomic ./ ./lifecycle ./render ./actions ./smode ./helpers
      - cat /tmp/coverage.txt.tmp | grep -v "backward." > {{ .CLI_ARGS }}
      - rm /tmp/coverage.txt.tmp

  docs:v1:
    cmds:
      - (cd docs/v1; mkdocs serve)
