version: 3

tasks:

  build:client:
    cmds:
      - (cd client && npm i && npm run dynamics)

  test:
    cmds:
      - go test -race .

  test:cov:
    cmds:
      - go test -cover .

  test:cov:web:
    cmds:
      - go test -coverprofile /tmp/kyoto-coverage.out .
      - go tool cover -html=/tmp/kyoto-coverage.out
      - sleep 3 && rm /tmp/kyoto-coverage.out

  test:cov:report:
    cmds:
      - go test -race -coverprofile=/tmp/coverage.txt.tmp -covermode=atomic .
      - cat /tmp/coverage.txt.tmp | grep -v "compat." > {{ .CLI_ARGS }}
      - rm /tmp/coverage.txt.tmp

  doc:
    cmds:
      - (sleep 1 && open http://localhost:8000/pkg/git.sr.ht/~kyoto-framework/kyoto/) &
      - godoc -http=:8000
