

title: SSC Documentation
description: Develop frontend Server Side Components with Go
base: /docs/

themeConfig:
  displayAllHeaders: true
  nav:
    - text: GitHub
      link: https://github.com/yuriizinets/go-ssc
  sidebar:
    - title: Overview
      path: /overview
    - title: Quick Start
      path: /quickstart
      sidebarDepth: 2
    - title: Concepts
      path: /concepts
      sidebarDepth: 2
    - title: Core
      path: /core
      sidebarDepth: 2
    - title: Extended
      path: /extended
      sidebarDepth: 2