name: Docs Workflow

on:
  push:
    branches:
      - master

jobs:

  v0:
    name: Docs v0
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:

    - name: Check Out
      uses: actions/checkout@v2

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push
      run: |
        (
          export CPATH=docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${REPOSITORY_NAME,,}-docs-v0;
          cd docs/v0;
          docker build -t $CPATH:latest .;
          docker push $CPATH:latest;
        )

  v1:
    name: Docs v1
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:

    - name: Check Out
      uses: actions/checkout@v2

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push
      run: |
        (
          export CPATH=docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${REPOSITORY_NAME,,}-docs-v1;
          cd docs/v1;
          docker build -t $CPATH:latest .;
          docker push $CPATH:latest;
        )
