name: Tests and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
      - name: Run tests with coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./ ./lifecycle ./render ./actions ./smode ./helpers
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
