name: Tests and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.txt.tmp -covermode=atomic ./ ./lifecycle ./render ./actions ./smode ./helpers
          cat coverage.txt.tmp | grep -v "backward." > coverage.txt
          rm coverage.txt.tmp
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
