name: Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install Taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Test
        run: task test
      - name: Test with coverage report
        run: task coverage:report -- coverage.txt
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
